module.exports = {
  apps: [
    {
      name: "auth-service",
      script: "src/index.js",
      cwd: "./services/auth-services",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      env: { NODE_ENV: "development" },
      env_production: { NODE_ENV: "production" },
    },
    {
      name: "notification-service",
      script: "index.js",
      cwd: "./services/notification-services",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      env: { NODE_ENV: "development" },
      env_production: { NODE_ENV: "production" },
    },
    {
      name: "ekyc-service",
      script: "index.js",
      cwd: "./services/ekyc-services",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      env: { NODE_ENV: "development" },
      env_production: { NODE_ENV: "production" },
    },
    {
      name: "file-service",
      script: "index.js",
      cwd: "./services/file-service",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      env: { NODE_ENV: "development" },
      env_production: { NODE_ENV: "production" },
    },
    {
      name: "api-gateway",
      script: "index.js",
      cwd: "./services/api-gateway",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      env: { NODE_ENV: "development" },
      env_production: { NODE_ENV: "production" },
    },
  ],
};
